Patch back grep line for number of trace records

diff --git a/buildspecs/apps/hpctoolkit/hpctoolkit_cuda_vecadd_perlmutter.yml b/buildspecs/apps/hpctoolkit/hpctoolkit_cuda_vecadd_perlmutter.yml
--- a/buildspecs/apps/hpctoolkit/hpctoolkit_cuda_vecadd_perlmutter.yml
+++ b/buildspecs/apps/hpctoolkit/hpctoolkit_cuda_vecadd_perlmutter.yml
@@ -19,24 +19,20 @@ buildspecs:
 
       rm -rf $out.m
       srun -n 1 -c 1 -G 1 hpcrun -e REALTIME -e gpu=nvidia -t -o $out.m ./cuda_vecadd $n || exit $?
+
+      # Expect at least 100 GPU trace records total
+      if [ "$(grep 'accelerator trace records:' $out.m/*.log | grep --only-matching 'processed: [[:digit:]]\+' | awk '{print $2}')" -lt 100 ]; then
+        echo "FAIL: Not enough trace records!"
+        exit 3
+      fi
+
       srun -n 1 -c 64 -G 0 hpcstruct $out.m || exit $?      
       rm -rf $out.d
       srun -n 1 -c 64 -G 0 hpcprof -o $out.d $out.m || exit $?
 
-    metrics:
-      accelerator_samples:
-        type: int
-        file_regex:
-          file: "hpctoolkit-vecadd.m/*.log"
-          exp: '.processed: [[:digit:]]\+'
-          item: 1
-
     status:
       mode: "all"
       returncode: 0
-      assert_ge:
-      - name: accelerator_samples
-        ref: 100
       file_count:
       - dir: "hpctoolkit-vecadd.m"
         ext: ".hpcrun"
